# Generated by Django 3.0.6 on 2020-05-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0003_auto_20200520_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tagname',
        ),
    ]
