# Generated by Django 3.0.6 on 2020-05-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0004_auto_20200520_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
