# Generated by Django 3.0.6 on 2020-05-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0005_remove_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='manage_product.Tag'),
        ),
    ]
