# Generated by Django 3.0.6 on 2020-05-21 02:59

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0006_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
