# Generated by Django 3.0.6 on 2020-05-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0013_auto_20200521_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
